Repository david-fisher/320-S21-Track2, pull requests merged in 2021-03, with the labels that each got.

#20 Docker testing
  Ghost_in_the_Shell/client_folder_react_app/ethisim/Dockerfile
  README.md
  docker-compose-deploy.yaml
  docker-compose.yaml
  moral_kombat_backend/Dockerfile
Labels: Moby-Dock

#43 Created Dashboard page to be loaded on user login
  Ghost_in_the_Shell/client_folder_react_app/ethisim/package-lock.json
  simulator/frontend/package-lock.json
  simulator/frontend/package.json
  simulator/frontend/src/App.js
  simulator/frontend/src/Nav.js
  simulator/frontend/src/pages/components/Banners/ErrorBanner.js
  simulator/frontend/src/pages/components/Banners/SuccessBanner.js
  simulator/frontend/src/pages/components/Copyright.js
  simulator/frontend/src/pages/components/DashboardComponents/DashboardNavbar.js
  simulator/frontend/src/pages/components/DashboardComponents/DropdownMenu.js
  simulator/frontend/src/pages/components/DashboardComponents/ShareButton.js
  simulator/frontend/src/pages/components/DashboardComponents/SimScenarioCard.js
  simulator/frontend/src/pages/components/DeleteWarnings/DeleteEntireScenarioWarning.js
  simulator/frontend/src/pages/components/DeleteWarnings/GenericDeleteWarning.js
  simulator/frontend/src/pages/components/LoadingSpinner.js
  simulator/frontend/src/pages/components/gatheredList.js
  simulator/frontend/src/pages/home.js
  simulator/frontend/src/pages/introduction.js
  simulator/frontend/src/pages/sim_dashboard.js
  simulator/frontend/src/pages/simulationWindow.js
  simulator/frontend/src/universalHTTPRequests/delete.js
  simulator/frontend/src/universalHTTPRequests/get.js
  simulator/frontend/src/universalHTTPRequests/post.js
  simulator/frontend/src/universalHTTPRequests/put.js
  simulator/goon-universe/package-lock.json
Labels: Doge, bug, enhancement

#98 Loading Issues into IC Matrix
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConfigureIssuesComponents/IssueCoverageMatrix.js
Labels: Git-Kings

#107 Update Issue Coverage Matrix
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConfigureIssuesComponents/IssueCoverageMatrix.js
Labels: Git-Kings
