Repository david-fisher/320-S21-Track2, pull requests merged in 2021-04, with the labels that each got.

#154 Merge Git-Kings into Main Branch
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/ConfigurationSideBarComponents/NavSideBarNode.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ActionPageComponents/Action.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConfigureIssuesComponents/ConfigureIssues.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConfigureIssuesComponents/IssueCoverageMatrix.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConversationEditorComponents/StakeHoldersComponent/StakeHolderQuestions/question.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ConversationEditorComponents/StakeHoldersComponent/StakeHolderQuestions/questions.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/FlowDiagramComponents/FlowDiagram.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/GenericPageComponents/Generic.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/GenericPageComponents/Introduction.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/LogisticsPageComponents/Logistics.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ReflectionPageComponents/Reflection.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/EditorComponents/ToDoListDialog.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/components/InfoButtons/GenericInfoButton.js
  Ghost_in_the_Shell/client_folder_react_app/ethisim/src/pages/editor.js
Labels: Git-Kings

#187 Page change
  simulator/frontend/src/pages/page_factory.js
  simulator/frontend/src/pages/simulator_window.js
Labels: Doge

#217 Fix stakeholders
  simulator/frontend/src/pages/action.js
  simulator/frontend/src/pages/components/checkbox.js
  simulator/frontend/src/pages/conversation.js
  simulator/frontend/src/pages/introduction.js
  simulator/frontend/src/pages/simulator_window.js
  simulator/frontend/src/pages/stakeholders.js
Labels: Doge, bug

#196 Fix page change
  simulator/frontend/src/pages/action.js
  simulator/frontend/src/pages/components/checkbox.js
  simulator/frontend/src/pages/simulator_window.js
Labels: Doge, bug
